# Test config: duplicate port (should produce warning)
# Eval: "try to setup the same port multiple times. It should not work."

server {
	listen 8080;
	server_name localhost;

	location / {
		root www;
		index index.html;
		methods GET;
	}
}

server {
	listen 8080;
	server_name localhost;

	location / {
		root www;
		index index.html;
		methods GET;
	}
}
